export const mock = {
  "data": {
      "meta": {
          "title": "Live Rugby API -  Fixtures for 2025-01-10",
          "description": "Fixtures and results for 2025-01-10",
          "fields": {
              "id": "Integer - unique fixture id, use to query match endpoint",
              "comp_id": "Integer",
              "comp_name": "String",
              "season": "Integer",
              "date": "Timestamp - ISO 8601 - always UTC",
              "game_week": "Integer",
              "home": "String",
              "away": "String",
              "home_id": "Integer",
              "away_id": "Integer",
              "status": "String - Not Started, First Half, Half Time, Second Half, Full Time, Postponed, Cancelled, Result",
              "venue": "String",
              "home_score": "Integer",
              "away_score": "Integer",
              "updated": "Timestamp - IS0 8601 - always UTC"
          }
      },
      "results": [
          {
              "id": 8487448,
              "comp_id": 1278,
              "comp_name": "Pro D2",
              "season": "2025",
              "date": "2025-01-10T18:00:00+00:00",
              "game_week": 16,
              "home": "Biarritz Olympique",
              "away": "Soyaux Angouleme",
              "home_id": 5717,
              "away_id": 1337,
              "status": "Result",
              "venue": "Parc des Sports Aguilera",
              "home_score": 10,
              "away_score": 25,
              "home_tries": 2,
              "away_tries": 4,
              "round_id": 16,
              "stage": "Regular Season",
              "updated": "2025-01-10T20:00:05+00:00"
          },
          {
              "id": 8487439,
              "comp_id": 1278,
              "comp_name": "Pro D2",
              "season": "2025",
              "date": "2025-01-10T18:30:00+00:00",
              "game_week": 16,
              "home": "Beziers",
              "away": "Nice",
              "home_id": 7517,
              "away_id": 91436,
              "status": "Result",
              "venue": "Stade Raoul-Barriere",
              "home_score": 42,
              "away_score": 9,
              "home_tries": 5,
              "away_tries": 0,
              "round_id": 16,
              "stage": "Regular Season",
              "updated": "2025-01-10T21:00:05+00:00"
          },
          {
              "id": 8487466,
              "comp_id": 1278,
              "comp_name": "Pro D2",
              "season": "2025",
              "date": "2025-01-10T18:30:00+00:00",
              "game_week": 16,
              "home": "Oyonnax",
              "away": "Aurillac",
              "home_id": 143,
              "away_id": 167,
              "status": "Result",
              "venue": "Stade Charles-Mathon",
              "home_score": 25,
              "away_score": 10,
              "home_tries": 3,
              "away_tries": 1,
              "round_id": 16,
              "stage": "Regular Season",
              "updated": "2025-01-10T21:00:13+00:00"
          },
          {
              "id": 8487475,
              "comp_id": 1278,
              "comp_name": "Pro D2",
              "season": "2025",
              "date": "2025-01-10T18:30:00+00:00",
              "game_week": 16,
              "home": "Agen",
              "away": "Provence Rugby",
              "home_id": 9467,
              "away_id": 80,
              "status": "Result",
              "venue": "Stade Armandie",
              "home_score": 10,
              "away_score": 17,
              "home_tries": 1,
              "away_tries": 1,
              "round_id": 16,
              "stage": "Regular Season",
              "updated": "2025-01-10T21:00:23+00:00"
          },
          {
              "id": 8487493,
              "comp_id": 1278,
              "comp_name": "Pro D2",
              "season": "2025",
              "date": "2025-01-10T18:30:00+00:00",
              "game_week": 16,
              "home": "USO Nevers",
              "away": "Mont de Marsan",
              "home_id": 434,
              "away_id": 149,
              "status": "Result",
              "venue": "Stade du Pre Fleuri",
              "home_score": 34,
              "away_score": 0,
              "home_tries": 4,
              "away_tries": 0,
              "round_id": 16,
              "stage": "Regular Season",
              "updated": "2025-01-10T21:00:31+00:00"
          },
          {
              "id": 8487502,
              "comp_id": 1278,
              "comp_name": "Pro D2",
              "season": "2025",
              "date": "2025-01-10T18:30:00+00:00",
              "game_week": 16,
              "home": "Valence Romans",
              "away": "Colomiers",
              "home_id": 2699,
              "away_id": 86,
              "status": "Result",
              "venue": "Stade Georges-Pompidou",
              "home_score": 24,
              "away_score": 29,
              "home_tries": 3,
              "away_tries": 4,
              "round_id": 16,
              "stage": "Regular Season",
              "updated": "2025-01-10T21:00:37+00:00"
          },
          {
              "id": 8487484,
              "comp_id": 1278,
              "comp_name": "Pro D2",
              "season": "2025",
              "date": "2025-01-10T20:00:00+00:00",
              "game_week": 16,
              "home": "Dax",
              "away": "CA Brive",
              "home_id": 185,
              "away_id": 10517,
              "status": "Result",
              "venue": "Stade Maurice Boyau",
              "home_score": 22,
              "away_score": 9,
              "home_tries": 3,
              "away_tries": 0,
              "round_id": 16,
              "stage": "Regular Season",
              "updated": "2025-01-10T23:00:28+00:00"
          },
          {
              "id": 8490481,
              "comp_id": 1464,
              "comp_name": "Investec Champions Cup",
              "season": "2025",
              "date": "2025-01-10T20:00:00+00:00",
              "game_week": 3,
              "home": "Glasgow Warriors",
              "away": "Racing 92",
              "home_id": 5267,
              "away_id": 140,
              "status": "Result",
              "venue": "Scotstoun Stadium",
              "home_score": 29,
              "away_score": 19,
              "home_tries": 5,
              "away_tries": 3,
              "round_id": 3,
              "stage": "Pool 4",
              "updated": "2025-01-10T23:00:06+00:00"
          },
          {
              "id": 8491003,
              "comp_id": 1470,
              "comp_name": "EPCR Challenge Cup",
              "season": "2025",
              "date": "2025-01-10T20:00:00+00:00",
              "game_week": 3,
              "home": "Gloucester Rugby",
              "away": "Scarlets",
              "home_id": 3317,
              "away_id": 5117,
              "status": "Result",
              "venue": "Kingsholm",
              "home_score": 31,
              "away_score": 7,
              "home_tries": 5,
              "away_tries": 1,
              "round_id": 3,
              "stage": "Pool 3",
              "updated": "2025-01-10T23:00:16+00:00"
          }
      ]
  },
  "status": 200,
  "statusText": "OK",
  "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-origin": "http://localhost:3000",
      "cache-control": "no-cache, private",
      "connection": "keep-alive",
      "content-length": "3976",
      "content-type": "application/json",
      "date": "Fri, 10 Jan 2025 23:42:30 GMT",
      "server": "RapidAPI-1.2.8",
      "x-rapidapi-region": "AWS - eu-central-1",
      "x-rapidapi-request-id": "0a0dcf8aca4621d32c036c72734b39de97eccd938791ef30388c695ae8c9be13",
      "x-rapidapi-version": "1.2.8",
      "x-ratelimit-rapid-free-plans-hard-limit-limit": "500000",
      "x-ratelimit-rapid-free-plans-hard-limit-remaining": "499986",
      "x-ratelimit-rapid-free-plans-hard-limit-reset": "2673329",
      "x-ratelimit-requests-limit": "250",
      "x-ratelimit-requests-remaining": "231",
      "x-ratelimit-requests-reset": "2673329"
  },
  "config": {
      "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
      },
      "adapter": [
          "xhr",
          "http",
          "fetch"
      ],
      "transformRequest": [
          null
      ],
      "transformResponse": [
          null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
          "Accept": "application/json, text/plain, */*",
          "x-rapidapi-key": "10d3d95232mshf07d6c711a45b57p1756a4jsn12fb112a270f",
          "x-rapidapi-host": "rugby-live-data.p.rapidapi.com"
      },
      "method": "get",
      "url": "https://rugby-live-data.p.rapidapi.com/fixtures-by-date/2025-01-10"
  },
  "request": {}
}