import "normalize.css/normalize.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { memo } from "react";
import { config } from "@fortawesome/fontawesome-svg-core";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { roboto } from "@/utils";
import Providers from "./providers";
import styles from "./index.module.scss";

/* 
Disable automatic CSS injection from FontAwesome to prevent style duplication
and potential hydration issues in SSR (Next.js). We manually import the styles instead.
*/
config.autoAddCss = false;

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // Apply Roboto font on the server side using the class generated by next/font.
    // This prevents flash of unstyled text and ensures font is loaded
    // before client rendering.
    <html lang="en" className={roboto.variable}>
      <body className={styles.body}>
        <AppRouterCacheProvider>
          <Providers>{children}</Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

export default memo(RootLayout);
